# Actor-Critic training config for train.py
algo: actor_critic
env: CartPole-v1
episodes: 300
hidden_dim: 128
gamma: 0.98
lr: 0.001
seed: 0
device: cpu

# Logging
wandb: true
wandb_entity: 23281269-
wandb_project: RL Project
wandb_group: actor_critic
run_name: actor-critic-cartpole
